services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - sw_network
    volumes:
      - .:/app
  mysql_db:
    image: mirror2.chabokan.net/mysql:latest
    container_name: mysql_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${PUBLIC_DB_PORT}:3306
    networks:
      - sw_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  sw_network:

volumes:
  mysql_data: